### PR TITLE
Plugin manager

### PR DESCRIPTION
**Pull request by wolfthefallen**
This Pull Request updates the plugin manager to a plugin store!
The plugin manager will now attempt to pull information from the securestate\king-phisher-repository and display a list of plugins for the user to install.

Open the plugin manager to view the changes
image

- [x] Displays Catalogs sub repositories, and plugins in them
- [x] User can Install a plugin from the catalog
- [x] User can enable an installed plugin
- [x] User can uninstall an installed plugin
- [ ] If client cannot reach the internet, but has cached information on the catalog it will operate off that information, and showed installed plugins
- [x] Information is displayed for the plugin, catalog and repositories when selected in the expanded information section.
- [x] Will show if the plugin is compatible
- [x] In the information section the pop up over the compatible section will display packages and if they are meet.

### CODE REVIEW

**Comment by zeroSteiner** [comment]
I opened another PR to make some style changes. Use `.is_alive()` for threads, it's the same as `isAlive()`. I updated a bunch of documentation strings and added the `ClientCatalogManager` class so it's included.

I'm having some issues with testing this. When I go to install a plugin, the one that I click is not the one that is installed. I also got the following stack trace while testing.

```
Error Type: builtins.KeyError
Error Details: KeyError('hello_world',)
Error UID: ae2c0a57-2646-4e5e-83a8-b9b0e8f0ae99
RPC Error: N/A (Not a remote RPC error)
King Phisher Version: 1.9.0-beta5 (rev: a615ebee262e)
Platform Version: Linux: Fedora 26 Twenty Six
Python Version: 3.6.2
Gtk Version: 3.22.21
Timezone: America/New_York

Thread Information:
 => MainThread (alive=True daemon=False)
    pydevd.Writer (alive=True daemon=True)
    pydevd.Reader (alive=True daemon=True)
    pydevd.CommandThread (alive=True daemon=True)
    Thread-7 (alive=True daemon=True)
    Thread-6 (alive=True daemon=False)
    Thread-11 (alive=True daemon=True)
    Thread-12 (alive=True daemon=True)

Stack Trace:
Traceback (most recent call last):
  File "/home/steiner/Repositories/king-phisher/king_phisher/client/windows/plugin_manager.py", line 420, in signal_renderer_toggled_enable
    installed_plugin_info = self.config['plugins.installed'][named_row.id]
KeyError: 'hello_world'
```

**Comment by zeroSteiner** [comment]
Just double checked my results with commit d30dd84ab60386faed3c89bce628c7264b14da9c to ensure that I didn't introduce the bug with my changes and I can still consistently reproduce it. The steps are as follows:

* Open the plugin manager and wait for everything to load
* Expand the `securestate/king-phisher-plugins` catalog
* Expand the `Offical King Phisher Plugins` repo
* **Bug 1:** Go to the last, uninstalled plugin and click the install check box
* See that the plugin is not installed, but a different one is
* **Bug 2:** Now select a different plugin to view it's information and see a stack trace

**Comment by wolfthefallen** [comment]
I've been unable to reproduce these issues. Can you please provide me any additional steps to help me recreate these issues?

Tested with your changes

# steps taken:
## clean state:
- removed `~/.config/king-phisher/config.json`
- removed `~/.config/king-phisher/cache.json`
- removed `~/.config/king-phisher/plugins/`

## test steps #1
- loaded plugin manager, installed 'hello world`
- verified the plugin installed in plugin path `~/.config/king-phisher/plugins`
  -- correct plugin was installed
- enabled `hello world` plugin
  - `Hello World!` was printed to output showing it was the correct plugin and successfully enabled
- uninstalled it
- closed plugin window
- opened plugin window
- selected last uninstalled plugin, in this case `hello world`
  - no stack trace
- Selected another plugin and viewed information
  - no stack trace

## test steps #2
Went back to clean state

- loaded plugin manager, installed 'hello world`
- verified the plugin installed in plugin path `~/.config/king-phisher/plugins`
  -- correct plugin was installed
- enabled `hello world` plugin
  - `Hello World!` was printed to output showing it was the correct plugin and successfully enabled
- uninstalled it
- selected a different plugin and viewed information
- selected last uninstalled plugin, in this case `hello world`
  - no stack trace
- Selected another plugin and viewed information
  - no stack trace

**Comment by zeroSteiner** [comment]
Testing all checks out. I made one last commit that allows locally installed plugins to be removed from the treeview if they're replaced by a repo-backed plugin.

**Pull request merged**
